# Generated by Django 2.0.2 on 2018-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0003_auto_20180404_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistencia',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
