# Generated by Django 2.0.2 on 2018-04-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0006_auto_20180410_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistencia',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(21, 'Não aceite o orçamento'), (23, 'Facturado'), (34, 'Creditado ao cliente'), (33, 'Não reparado em armazem'), (31, 'Reparado em armazem'), (24, 'Sem avaria'), (20, 'Sem reparação'), (26, 'Garantia resolvido'), (27, 'Cliente resolveu'), (28, 'Resolvido comprou nova'), (18, 'Enviado para reciclagem'), (29, 'anulado'), (8, 'Aguardar contacto do cliente'), (14, 'Não pago'), (36, 'Facturado e Pago'), (30, 'Supostamente Resolvido'), (23, 'Facturado'), (2, 'Em resolução'), (19, 'Reparação sem valor'), (3, 'Resolvido')], default=2, null=True),
        ),
    ]
