# Generated by Django 2.0.2 on 2019-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencias', '0008_pessoa_rgpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
