# Use root/example as user/password credentials
version: "3.7"
services:
  web:
    image: nginx
    volumes:
     - ./web/rma_mlp:/etc/nginx/conf.d/rma.local.conf
     - ../django/static:/home/miguel/django/static
    expose:
      - 80
    environment:
     - VIRTUAL_HOST=rma.local 
    links: 
      - python_migest
    restart: always
  python_migest:
    build:
      context: .
      dockerfile: ./python_migest/Dockerfile
    volumes:
      - ../django:/home/miguel/django
    #command: bash -c "cd /home/miguel/django/mlpbarreiro && gunicorn -b 0.0.0.0:8000 mlpbarreiro.wsgi"
    #command: bash -c "python /home/miguel/django/mlpbarreiro/manage.py migrate
     #        && python /home/miguel/django/mlpbarreiro/manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python /home/miguel/django/mlpbarreiro/manage.py runserver 0.0.0.0:8000"
    command: bash -c "cd /home/miguel/django/mlpbarreiro && gunicorn --bind 0.0.0.0:8001 mlpbarreiro.wsgi"
    depends_on: 
      - db_migest
    expose: 
      - 8001
    restart: always
  db_migest:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - dbdata:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    expose:
      - 8080
    environment: 
      - VIRTUAL_HOST=adminer.local
      - VIRTUAL_PORT=8080
volumes: 
  dbdata: