# Use root/example as user/password credentials
version: "3.7"
services:
  python_migest:
    build:
      context: .
      dockerfile: ./python_migest/Dockerfile
    volumes:
      - ../django:/home/miguel/django
    #command: bash -c "cd /home/miguel/django/mlpbarreiro && gunicorn --bind 0.0.0.0:8001 mlpbarreiro.wsgi"
    command: bash -c "cd /home/miguel/django/mlpbarreiro && python manage.py runserver 0:8000"
    depends_on: 
      db_migest:
        condition: service_healthy
    ports: 
      - 8000:8000
    restart: always
  db_migest:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: migest
      MYSQL_USER: miguel
      MYSQL_PASSWORD: example
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - 33006:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
volumes: 
  dbdata: