# Use root/example as user/password credentials
version: "3.7"
services:
  python_migest:
    build:
      context: .
      dockerfile: ./python_migest/Dockerfile
    volumes:
      - ../django:/home/miguel/django
    ports:
      - 8000:8000
    #command: bash -c "cd /home/miguel/django/mlpbarreiro && gunicorn -b 0.0.0.0:8000 mlpbarreiro.wsgi"
    command: bash -c "cd /home/miguel/django/mlpbarreiro && python manage.py runserver 0.0.0.0:8000"
    links:
      - db_migest
  db_migest:
    image: mysql:5.6
    volumes:
      - ./mlp_assist.sql:/mysql_data/ml_assist.sql
      - migest-datavolume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - mysql.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  migest-datavolume: